---
apiVersion: v1
kind: Namespace
metadata:
  name: share

---
apiVersion: v1
kind: Namespace
metadata:
  name: helm

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-releases
  namespace: helm

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helm-releases-role
  namespace: helm
rules:
- apiGroups:
  - ''
  - 'apps'
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-releases-rolebinding
  namespace: helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: helm-releases-role
subjects:
- kind: ServiceAccount
  name: helm-releases
  namespace: helm

---
apiVersion: yaho.soer3n.dev/v1alpha1
kind: Config
metadata:
  name: helm-release-config
  namespace: helm
spec:
  serviceAccountName: helm-releases
  namespace:
    install: false
    allowed:
    - share
    - helm
  flags:
    atomic: false
    skipCRDs: false
    subNotes: true
    disableOpenAPIValidation: false
    dryRun: false
    disableHooks: false
    wait: false
    cleanupOnFail: false
    recreate: false
    timeout: 3600
    force: false
    description: "test description"
