---
apiVersion: yaho.soer3n.dev/v1alpha1
kind: Repository
metadata:
  name: test-repo
spec:
  name: test-repo
  url: https://soer3n.github.io/charts/testing_a
  charts: []

---
apiVersion: yaho.soer3n.dev/v1alpha1
kind: Chart
metadata:
  name: test-chart
spec:
  name: testing
  repository: test-repo
  versions:
  - 0.1.1
  createDeps: true
