apiVersion: helm.soer3n.info/v1alpha1
kind: Release
metadata:
  name: release
  namespace: helm
spec:
  name: nextcloud
  namespace: share
  config: nextcloud-config
  repo: nextcloud
  chart: nextcloud
  version: 2.6.5
  values:
  - values-nextcloud
  - values-redis
  - values-db-nextcloud
  - values-nginx-nextcloud
