---
apiVersion: yaho.soer3n.dev/v1alpha2
kind: Config
metadata:
  name: nextcloud-config
  namespace: helm
spec:
  serviceAccountName: yaho-config
  namespace:
    install: true
    allowed:
    - share
    - nextcloud
  flags:
    atomic: false
    skipCRDs: false
    subNotes: true
    disableOpenAPIValidation: false
    dryRun: false
    disableHooks: false
    wait: false
    cleanupOnFail: false
    recreate: false
    timeout: 3600
    force: false
    description: "test description"

---
apiVersion: v1
kind: Namespace
metadata:
  name: share

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: yaho-config
  namespace: helm

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yaho-config-role
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yaho-config-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: yaho-config-role
subjects:
- kind: ServiceAccount
  name: yaho-config
  namespace: helm