---
apiVersion: yaho.soer3n.dev/v1alpha2
kind: Hub
metadata:
  name: remote
spec:
  interval: 10s
  config: nextcloud-config.helm # default settings for releases, can also be specified in release cr
  agent:
    deploy: true
    name: yaho-agent
    namespace: helm
  selector:
    kind: Secret # can be Secret or ServiceAccount if in cluster address can be used
    # namespace: helm # if not specified the operator will watch in all namespaces
    labels:
      yaho.soer3n.dev/hub: "remote"
    key: kubeconfig
  defaults:
  - chart: cilium
    repo: cilium
    values: cilium-values.helm
  - chart: ingress-nginx
    repo: ingress-nginx
    values: ingress-nginx-values.helm
