apiVersion: v1
kind: Service
metadata:
  labels:
    "operators.soeren.dev": yaho
  name: controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    "operators.soeren.dev": yaho
