# permissions for end users to view releases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-viewer-role
rules:
- apiGroups:
  - helm.soer3n.info
  resources:
  - releases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - helm.soer3n.info
  resources:
  - releases/status
  verbs:
  - get
