# permissions for end users to view releasegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: releasegroup-viewer-role
rules:
- apiGroups:
  - helm.soer3n.info
  resources:
  - releasegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - helm.soer3n.info
  resources:
  - releasegroups/status
  verbs:
  - get
