# permissions for end users to edit repos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: repo-editor-role
rules:
- apiGroups:
  - yaho.soer3n.dev
  resources:
  - repos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - yaho.soer3n.dev
  resources:
  - repos/status
  verbs:
  - get
