# permissions for end users to view repos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: repo-viewer-role
rules:
- apiGroups:
  - helm.soer3n.info
  resources:
  - repos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - helm.soer3n.info
  resources:
  - repos/status
  verbs:
  - get
