# permissions for end users to edit repogroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: repogroup-editor-role
rules:
- apiGroups:
  - helm.soer3n.info
  resources:
  - repogroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helm.soer3n.info
  resources:
  - repogroups/status
  verbs:
  - get
