# permissions for end users to view repogroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: repogroup-viewer-role
rules:
- apiGroups:
  - helm.soer3n.info
  resources:
  - repogroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - helm.soer3n.info
  resources:
  - repogroups/status
  verbs:
  - get
