
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - helm.soer3n.info
  resources:
  - charts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helm.soer3n.info
  resources:
  - charts/finalizers
  verbs:
  - update
- apiGroups:
  - helm.soer3n.info
  resources:
  - charts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - helm.soer3n.info
  resources:
  - releasegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helm.soer3n.info
  resources:
  - releasegroups/finalizers
  verbs:
  - update
- apiGroups:
  - helm.soer3n.info
  resources:
  - releasegroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - helm.soer3n.info
  resources:
  - releases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helm.soer3n.info
  resources:
  - releases/finalizers
  verbs:
  - update
- apiGroups:
  - helm.soer3n.info
  resources:
  - releases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - helm.soer3n.info
  resources:
  - repogroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helm.soer3n.info
  resources:
  - repogroups/finalizers
  verbs:
  - update
- apiGroups:
  - helm.soer3n.info
  resources:
  - repogroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - helm.soer3n.info
  resources:
  - repos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - helm.soer3n.info
  resources:
  - repos/finalizers
  verbs:
  - update
- apiGroups:
  - helm.soer3n.info
  resources:
  - repos/status
  verbs:
  - get
  - patch
  - update
