# permissions for end users to edit values.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: values-editor-role
rules:
- apiGroups:
  - yaho.soer3n.dev
  resources:
  - values
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - yaho.soer3n.dev
  resources:
  - values/status
  verbs:
  - get
