# permissions for end users to view values.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: values-viewer-role
rules:
- apiGroups:
  - helm.soer3n.info
  resources:
  - values
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - helm.soer3n.info
  resources:
  - values/status
  verbs:
  - get
