# permissions for end users to edit hubs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hub-editor-role
rules:
- apiGroups:
  - yaho.soer3n.dev
  resources:
  - hubs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - yaho.soer3n.dev
  resources:
  - hubs/status
  verbs:
  - get
