#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  labels:
#    control-plane: controller-manager
#  name: harbor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaho-controller-manager
  namespace: harbor
  labels:
    control-plane: yaho-controller-manager
spec:
  selector:
    matchLabels:
      control-plane: yaho-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: yaho-controller-manager
    spec:
      imagePullSecrets:
      - name: harbor-registry-secret
      serviceAccountName: yaho-runner
      securityContext:
        runAsUser: 65532
      containers:
      - command:
        - /manager
        args:
        - operator
        image: ${IMG}
        name: yaho-manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 10
