apiVersion: helm.soer3n.info/v1alpha1
kind: Repo
metadata:
  name: testing
  namespace: helm
spec:
  name: testing
  url: https://hub.soer3n.info/chartrepo/public
  auth:
    user: soer3n
    pw: Ju?3ahsi
