apiVersion: helm.soer3n.info/v1alpha1
kind: RepoGroup
metadata:
  name: repogroup-sample
spec:
  labelSelector: foo
  repos:
    - name: nextcloud
      url: https://nextcloud.github.io/helm/
    - name: bitnami
      url: https://charts.bitnami.com/bitnami
