apiVersion: yaho.soer3n.dev/v1alpha1
kind: RepoGroup
metadata:
  name: repogroup-sample
  namespace: helm
spec:
  labelSelector: foo
  repos:
    - name: nextcloud
      url: https://soer3n.github.io/charts/testing_a
