kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # the default CNI will not be installed
  disableDefaultCNI: false
  apiServerAddress: 127.0.0.1
  apiServerPort: 30001
  podSubnet: "10.245.0.0/16"
  serviceSubnet: "10.246.0.0/16"
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /plugins/bin
    containerPath: /opt/cni/bin
  - hostPath: /dev/mapper
    containerPath: /dev/mapper
- role: worker
- role: worker
