---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev-cluster
nodes:
- role: control-plane
# - role: worker
# - role: worker

networking:
  # the default CNI will not be installed
  disableDefaultCNI: false
  kubeProxyMode: "ipvs"
  serviceSubnet: "10.96.0.0/12"
  podSubnet: "10.244.0.0/16"
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  ipFamily: dual
