apiVersion: helm.soer3n.info/v1alpha1
kind: Release
metadata:
  name: release
  namespace: helm
spec:
  name: nextcloud
  namespace:
    install: true
    name: share
  repo: nextcloud
  chart: nextcloud
  version: 2.6.5
  releaseSpec:
    valueRefs:
    - values-nextcloud
    - values-redis
    - values-db-nextcloud
    - values-nginx-nextcloud
    deps:
      mariadb:
        enabled: false
      postgresql:
        enabled: true
      redis:
        enabled: false
