namespace: helm
resources:
- local-agent.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: agent-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: soer3n/yaho
  newName: soer3n/yaho
  newTag: 0.0.3
