---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-agent
  labels:
    "operators.soeren.dev": yaho
spec:
  selector:
    matchLabels:
      "operators.soeren.dev": yaho
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: agent
      labels:
        "operators.soeren.dev": yaho
    spec:
      securityContext:
        runAsUser: 65532
      containers:
      - command:
        - /manager
        - agent
        - run
        args:
        - --leader-elect
        image: soer3n/yaho:0.0.2
        name: agent
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 768Mi
          requests:
            cpu: 10m
            memory: 256Mi
      serviceAccountName: controller-agent
      terminationGracePeriodSeconds: 10
