# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/yaho.soer3n.dev_repositories.yaml
- bases/yaho.soer3n.dev_repogroups.yaml
- bases/yaho.soer3n.dev_releases.yaml
- bases/yaho.soer3n.dev_releasegroups.yaml
- bases/yaho.soer3n.dev_charts.yaml
- bases/yaho.soer3n.dev_values.yaml
- bases/yaho.soer3n.dev_configs.yaml
- bases/yaho.soer3n.dev_hubs.yaml
# +kubebuilder:scaffold:crdkustomizeresource

#patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_repogroups.yaml
#- patches/webhook_in_releases.yaml
#- patches/webhook_in_releasegroups.yaml
#- patches/webhook_in_charts.yaml
#- patches/webhook_in_values.yaml
#- patches/webhook_in_configs.yaml
#- patches/webhook_in_hubs.yaml
#- patches/webhook_in_repositories.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_repogroups.yaml
#- patches/cainjection_in_releases.yaml
#- patches/cainjection_in_releasegroups.yaml
#- patches/cainjection_in_charts.yaml
#- patches/cainjection_in_values.yaml
#- patches/cainjection_in_configs.yaml
#- patches/cainjection_in_hubs.yaml
#- patches/cainjection_in_repositories.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
