apiVersion: yaho.soer3n.dev/v1alpha1
kind: Values
metadata:
  name: values-nginx-nextcloud
  namespace: helm
spec:
  json:
    nginx:
      ## You need to set an fpm version of the image for nextcloud if you want to use nginx!
      enabled: true
      image:
        repository: nginx
        tag: alpine
        pullPolicy: IfNotPresent

      config:
        # This generates the default nginx config as per the nextcloud documentation
        default: true
        custom: |-
          keepalive_timeout 10m;
          proxy_connect_timeout  20s;
          proxy_send_timeout  600s;
          proxy_read_timeout  150s;
          client_body_buffer_size 70m;
          client_header_buffer_size 50k;
          large_client_header_buffers 2 50k;
          client_max_body_size 0;

      resources: {}
