name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: build
      run: go build -v ./...

  test-unit:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: test packages
      run: go test -coverpkg ./internal/... ./tests/unit/...

  test-k8s:
    strategy:
      fail-fast: false
      matrix:
        version:
        - v1.26.0
        - v1.25.3
        - v1.24.7
        - v1.23.13
    runs-on: ubuntu-latest
    name: test-e2e-k8s-${{ matrix.version }}
    needs:
    - build
    steps:
    - uses: actions/checkout@v3
    - name: set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: create k8s Kind cluster
      uses: helm/kind-action@v1.2.0
      with:
        node_image: kindest/node:${{ matrix.version }}
        cluster_name:  cluster-${{ matrix.version }}
        config: testutils/kind.yaml
        version: v0.17.0
    - name: test controllers
      run: go test -coverpkg ./controllers/... ./tests/e2e/controller/...
