name: CI

on:
  push:
    branches:
      - master
  pull_request_review:
    types: [submitted]
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: build
      run: go build -buildvcs=false  -v ./...

  test-unit:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: test packages
      run: go test -coverpkg ./internal/... ./tests/unit/...

  test-k8s:
    strategy:
      fail-fast: false
      matrix:
        version:
        - v1.27.1
        - v1.26.3
        - v1.25.8
        - v1.24.12
        - v1.23.17
    runs-on: ubuntu-latest
    if: ${{ (github.event.review.state == 'approved') || github.ref == 'refs/heads/master' }}
    name: test-e2e-k8s-${{ matrix.version }}
    needs:
    - build
    steps:
    - uses: actions/checkout@v4
    - name: set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: create k8s Kind cluster
      uses: helm/kind-action@v1.8.0
      with:
        node_image: kindest/node:${{ matrix.version }}
        cluster_name:  cluster-${{ matrix.version }}
        config: testutils/kind.yaml
        version: v0.18.0
    - name: test controllers
      run: go test -coverpkg ./controllers/... ./tests/e2e/controller/...
