name: CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: build
      run: go build -v ./...

  test-unit:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: test packages
      run: go test -coverpkg ./internal/... ./tests/unit/...

  test-k8s:
    strategy:
      fail-fast: false
      matrix:
        version:
        - v1.23.5
        - v1.22.7
        - v1.21.10
        - v1.20.15
        - v1.19.16
    runs-on: ubuntu-latest
    name: test-e2e-k8s-${{ matrix.version }}
    needs:
    - build
    steps:
    - uses: actions/checkout@v3
    - name: set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: create k8s Kind cluster
      uses: helm/kind-action@v1.2.0
      with:
        node_image: kindest/node:${{ matrix.version }}
        cluster_name:  cluster-${{ matrix.version }}
        config: testutils/kind.yaml
    - name: test controllers
      run: go test -coverpkg ./controllers/... ./tests/e2e/controller/...
