name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17
    - name: create k8s Kind cluster
      uses: helm/kind-action@v1.2.0
      with:
        node_image: kindest/node:v1.20.7
        config: testutils/kind.yaml
    - name: set directories to cover
      run: echo "COVERPKG=$(go list ./... | grep -v apis | grep -v tests | tr '\n' ',')" >> $GITHUB_ENV
    - name: run coverage
      run: go test -covermode=atomic -race -coverprofile ./coverage.txt -coverpkg ${{ env.COVERPKG }} ./tests/...
    - name: report coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.txt
        fail_ci_if_error: true
