name: Lint

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: check out code
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          args: --issues-exit-code=1 --timeout=5m0s
          only-new-issues: true
