name: Release

on:
  push:
    branches:
      - "!*"
    tags:
      - "*"

jobs:

  docker_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.19

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_IO_TOKEN }}

    - name: set tag as output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Build and push operator image
      uses: docker/build-push-action@v5
      with:
        file: Dockerfile
        context: .
        push: true
        tags: soer3n/yaho:${{ steps.vars.outputs.tag }}

    - name: Build olm bundle
      run: make bundle
      env:
        VERSION: ${{ steps.vars.outputs.tag }}
        CHANNEL: stable-v0

    - name: Build and push bundle image
      uses: docker/build-push-action@v5
      with:
        file: bundle.Dockerfile
        context: .
        push: true
        tags: soer3n/yaho-bundle:${{ steps.vars.outputs.tag }}

    - name: Rebuild catalog manifest
      run: make catalog-build
      env:
        VERSION: ${{ steps.vars.outputs.tag }}
        CHANNEL: stable-v0

    - name: Rebuild catalog and update image
      uses: docker/build-push-action@v5
      with:
        file: olm/olm.Dockerfile
        context: olm/
        push: true
        tags: soer3n/yaho:catalog

    - name: Build release artifacts
      run: make artifacts-build
      env:
        VERSION: ${{ steps.vars.outputs.tag }}
        CHANNEL: stable-v0

    - name: Release artifacts
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/yaho-v${{ steps.vars.outputs.tag }}-deployment.yaml
          artifacts/yaho-v${{ steps.vars.outputs.tag }}-olm.yaml
